# Generated by Django 4.1.1 on 2022-10-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_category_image_category_svg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='svg',
            field=models.CharField(max_length=10000, verbose_name='вектор'),
        ),
    ]
