# Generated by Django 4.1.1 on 2022-12-13 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_svg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Прибыль')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='категория')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__name']},
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
