# Generated by Django 4.0.5 on 2022-06-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_by', models.JSONField()),
                ('id_buyer', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('total_price', models.IntegerField()),
                ('byt_at', models.DateTimeField(auto_now_add=True)),
                ('paid_for', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['byt_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('context', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/product')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['title'],
            },
        ),
    ]
